#!/bin/bash
# ============================================================
# ops/verify.sh  –  EquiProfile Post-Deploy Verification
# ============================================================
# Checks that the running app is healthy and serving correctly.
#
# Usage:
#   bash ops/verify.sh
#   BASE_URL=https://equiprofile.online bash ops/verify.sh
#
# Exit codes:
#   0  – all checks passed (or only soft-failure checks failed)
#   1  – a hard-required check failed

set -euo pipefail

BASE_URL="${BASE_URL:-https://equiprofile.online}"
LOCAL_URL="http://127.0.0.1:3000"

PASS=0
FAIL=0
WARN=0

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

ok()   { echo -e "  ${GREEN}✅ PASS${NC}  $1"; PASS=$((PASS+1)); }
fail() { echo -e "  ${RED}❌ FAIL${NC}  $1"; FAIL=$((FAIL+1)); }
warn() { echo -e "  ${YELLOW}⚠️  WARN${NC}  $1"; WARN=$((WARN+1)); }

http_code() {
  curl -o /dev/null -s -w "%{http_code}" --max-time 10 "$1" 2>/dev/null || echo "000"
}
body() {
  curl -fsS --max-time 10 "$1" 2>/dev/null || echo ""
}

echo "============================================================"
echo " EquiProfile Verification  –  $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
echo " BASE_URL: $BASE_URL"
echo "============================================================"
echo ""

# ── 1. Systemd service ─────────────────────────────────────
echo "── 1. Systemd service ─────────────────────────────────"
if systemctl is-active --quiet equiprofile 2>/dev/null; then
  ok "equiprofile.service is active"
else
  warn "equiprofile.service is not running (may not be systemd env)"
fi
echo ""

# ── 2. Local health endpoint ───────────────────────────────
echo "── 2. Local health endpoint ───────────────────────────"
CODE=$(http_code "$LOCAL_URL/api/health")
if [ "$CODE" = "200" ]; then
  ok "GET $LOCAL_URL/api/health → $CODE"
else
  fail "GET $LOCAL_URL/api/health → $CODE  (expected 200)"
fi
echo ""

# ── 3. Public health endpoint ──────────────────────────────
echo "── 3. Public health endpoint ──────────────────────────"
CODE=$(http_code "$BASE_URL/api/health")
if [ "$CODE" = "200" ]; then
  ok "GET $BASE_URL/api/health → $CODE"
else
  warn "GET $BASE_URL/api/health → $CODE  (DNS/TLS may not be set up)"
fi
echo ""

# ── 4. Static assets ───────────────────────────────────────
echo "── 4. Static assets ───────────────────────────────────"
for asset in "/" "/index.html"; do
  CODE=$(http_code "$LOCAL_URL$asset")
  if [ "$CODE" = "200" ]; then
    ok "GET $LOCAL_URL$asset → $CODE"
  else
    fail "GET $LOCAL_URL$asset → $CODE"
  fi
done

# build.txt is generated by build-fingerprint.sh (non-fatal if absent)
CODE=$(http_code "$LOCAL_URL/build.txt")
if [ "$CODE" = "200" ]; then
  ok "GET $LOCAL_URL/build.txt → $CODE"
else
  warn "GET $LOCAL_URL/build.txt → $CODE  (build fingerprint not generated)"
fi
echo ""

# ── 5. SSE endpoint handshake ──────────────────────────────
echo "── 5. SSE / real-time handshake ───────────────────────"
# A quick connect that reads 1 byte; 200 with text/event-stream means SSE is up
SSE_CODE=$(curl -o /dev/null -s -w "%{http_code}" --max-time 3 \
  -H "Accept: text/event-stream" "$LOCAL_URL/api/events" 2>/dev/null || echo "000")
case "$SSE_CODE" in
  200|401|403) ok "SSE endpoint $LOCAL_URL/api/events → $SSE_CODE  (auth required – endpoint exists)" ;;
  404)         warn "SSE endpoint not found at $LOCAL_URL/api/events (may use different path)" ;;
  *)           warn "SSE endpoint returned $SSE_CODE" ;;
esac
echo ""

# ── 6. Nginx config validity ───────────────────────────────
echo "── 6. Nginx configuration ─────────────────────────────"
if command -v nginx >/dev/null 2>&1; then
  if nginx -t 2>/dev/null; then
    ok "nginx -t passed"
  else
    fail "nginx -t FAILED"
    nginx -t 2>&1 | sed 's/^/   /' || true
  fi
else
  warn "nginx not installed on this machine"
fi
echo ""

# ── 7. Build artefacts present ─────────────────────────────
echo "── 7. Build artefacts ─────────────────────────────────"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

for f in "dist/index.js" "dist/public/index.html"; do
  if [ -f "$APP_DIR/$f" ]; then
    ok "$f present"
  else
    fail "$f MISSING"
  fi
done
echo ""

# ── Summary ────────────────────────────────────────────────
echo "============================================================"
echo " Results: ${PASS} passed  ${WARN} warnings  ${FAIL} failed"
echo "============================================================"

if [ "$FAIL" -gt 0 ]; then
  echo ""
  echo "❌  ${FAIL} check(s) failed."
  echo ""
  echo "Diagnostics:"
  echo "  journalctl -u equiprofile -n 120 --no-pager"
  echo "  nginx -t"
  echo "  cat /var/log/equiprofile-deploy.log"
  exit 1
else
  echo ""
  echo "✅  All required checks passed."
fi
